Update to oniguruma 6.7.1
The primary reason for the update is to fix the build on MacOS.
During the build it was receiving this error:

posix.c:94:3: error: implicit declaration of function 'onig_end'
is invalid in C99 [-Werror,-Wimplicit-function-declaration]
onig_end();

This was later fixed in the oniguruma repo on this commit:
https://github.com/kkos/oniguruma/commit/5a24a49d710a9e3bb8ff11d12e1eae5a9f9df40c